added base infrastracture and layout
presence-solutions/mqtt-room-presence pull request #2
Opened 2021-12-02 00:13 UTC by vkosovskikh

2022-01-17 08:09 UTC, c58 requested changes
В целом круто! Несколько вопросов и замечаний

2022-01-17 08:09 UTC, c58 commented on package.json
> +  "author": "Artem Artemev <artem@artemevs.com>",
Добавь себя в авторы

2022-01-17 11:11 UTC, vkosovskikh commented on client/schema.graphql
> +type ExecutionError {
В общем, суть в том, что мы хотим типы из схемы перевести в TS. Тут я использовал отдельный инструмент для кодгена - graphql-code-generator. Потому, что у urql, который я выбрал в качестве клиента graphql нету встроенного кодгена. А выбрал я urql потому, что Relay и Apollo - это два куска говна, на которые я потратил два дня и так и не смог их завести. А urql за пару часов запустил.

2022-01-17 11:13 UTC, vkosovskikh commented on client/src/api/scanners.graphql
> +}
Это я руками писал, codegen так же берет эти запросы и генерит по хуку на каждый запрос, уже с типами.

2022-01-17 11:16 UTC, vkosovskikh commented on client/src/containers/HomePage/DevicesPage/DevicesPage.tsx
> +    }).then((result) => {
urql почему-то для мутаций ошибку кладет именно в result. То есть нет, здесь реджекта не будет, на ошибку проверка чуть ниже.

2022-01-17 11:19 UTC, vkosovskikh commented on client/src/containers/HomePage/HomePage.tsx
> +            text={fm('HomePage_RoomsLink')}
Сейчас для переводов написан кастомный хук с типами, который знает какие строки можно вводить. То есть и автокомплит работает и будет ругаться, если не то ввести. Мне кажется этого хватит. Как думаешь?

2022-01-17 11:35 UTC, vkosovskikh commented on client/src/containers/HomePage/RoomsPage/RoomsModal.tsx
> +        onAddRoom(values.roomName);
Подумаю

2022-01-17 16:31 UTC, c58 commented on client/src/api/scanners.graphql
> +}
хорошо, как они тут оказались понятно, но нужно ли их синхронизировать со схемой которая в руте? если да, то есть ли варианты как обойтись без этого?

2022-01-18 01:53 UTC, vkosovskikh commented on client/schema.graphql
> +type ExecutionError {
А, я не заметил, что в корне уже есть. Попробую его использовать

2022-01-18 01:58 UTC, vkosovskikh commented on client/src/api/scanners.graphql
> +}
Что ты имеешь ввиду под синхронизировать? Типа если схема изменится, то нужно будет запросы переписывать? Да, нужно будет. Вряд ли можно этот процесс улучшить. В любом случае, эти queries пришлось бы в коде в строках писать, но тогда запросы были бы не типизированными. А через кодген с типами получается.

2022-01-18 10:17 UTC, c58 commented on client/src/api/scanners.graphql
> +}
А, это запросы, сразу не отобразил, я думал это схема опять распиленная на части :) тогда все путем

2022-01-24 07:47 UTC, c58 approved these changes

2022-01-24 07:48 UTC, merged